In [57]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
import numpy as np

# Example 1

Convolutional Neural Network with 2D Input
Input: 5x5
Con2D: Kernel=1, Size=3x3, Stride=1
Flatten:
SingleNeuron:

In [72]:
x_train = np.array([[0.02, 0.21, 0.07, 0.17, 0.78],
                          [0.09, 0.25, 0.78, 0.04, 0.24],
                          [0.97, 0.29, 0.37, 0.27, 0.82],
                          [1.00, 0.29, 0.75, 0.62, 0.56],
                          [0.88, 0.65, 0.09, 0.99, 0.87]])
x_train = x_train.reshape((1,5,5,1))
y_train = np.array([0.5])

print(x_train.shape)
print(y_train.shape)

(1, 5, 5, 1)
(1,)


In [73]:
dense_weights = np.array([[0.99, 0.93, 0.83, 0.49, 0.59, 0.3, 0.96, 0.72, 0.8]])
dense_weights = dense_weights.reshape(9,1)
dense_bias = np.array([1.5])
dense_para = [dense_weights, dense_bias]
print(dense_para)

[array([[0.99],
       [0.93],
       [0.83],
       [0.49],
       [0.59],
       [0.3 ],
       [0.96],
       [0.72],
       [0.8 ]]), array([1.5])]


In [74]:
Conv2D_weights = np.array([[[0.12, 0.89, 0.21], [0.04, 0.64, 0.13], [0.91, 0.05, 0.64]]])
Conv2D_weights = Conv2D_weights.reshape(3,3,1,1)
Conv2D_bias = np.array([1])
Conv2D_para = [Conv2D_weights, Conv2D_bias]
print(Conv2D_para)

[array([[[[0.12]],

        [[0.89]],

        [[0.21]]],


       [[[0.04]],

        [[0.64]],

        [[0.13]]],


       [[[0.91]],

        [[0.05]],

        [[0.64]]]]), array([1])]


In [75]:
model = Sequential()
model.add(layers.Conv2D(filters=1,kernel_size=3,strides=1,padding='valid',input_shape=(5,5,1),activation="sigmoid"))
model.layers[0].set_weights(Conv2D_para)
print(model.summary())
print(model.predict(x_train))
model.add(layers.Flatten())
print(model.summary())
model.add(layers.Dense(1, activation="sigmoid"))
model.layers[2].set_weights(dense_para)
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 3, 3, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
None
[[[[0.9310544 ]
   [0.89020145]
   [0.9077528 ]]

  [[0.9558117 ]
   [0.93786526]
   [0.9272841 ]]

  [[0.9350025 ]
   [0.961676  ]
   [0.9336836 ]]]]
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_10 (Conv2D)           (None, 3, 3, 1)           10        
_________________________________________________________________
flatten_7 (Flatten)          (None, 9)                 0         
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
None
Model: "seq

In [76]:
# compile model (configure training process)
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.25, momentum=0.0, nesterov=False), loss='mean_squared_error')

In [77]:
model.fit(x_train, y_train, epochs=1)

Train on 1 samples
1/1 [==============================] - 0s 340ms/sample - loss: 0.2495


In [78]:
model.layers[0].get_weights()

[array([[[[0.11998391]],
 
         [[0.88998747]],
 
         [[0.20998009]]],
 
 
        [[[0.0399732 ]],
 
         [[0.63997823]],
 
         [[0.12997703]]],
 
 
        [[[0.90997213]],
 
         [[0.04997546]],
 
         [[0.6399726 ]]]], dtype=float32),
 array([0.99994797], dtype=float32)]

# Example 2

Convolutional Neural Network with 2D Input
Input: 5x5
Con2D: Kernel=1, Size=3x3, Stride=1
Con2D: Kernel=1, Size=3x3, Stride=1
Flatten:
SingleNeuron:

In [ ]:
x_train = np.array([[0.02, 0.21, 0.07, 0.17, 0.78],
                          [0.09, 0.25, 0.78, 0.04, 0.24],
                          [0.97, 0.29, 0.37, 0.27, 0.82],
                          [1.00, 0.29, 0.75, 0.62, 0.56],
                          [0.88, 0.65, 0.09, 0.99, 0.87]])
x_train = x_train.reshape((1,5,5,1))
y_train = np.array([0.5])

print(x_train.shape)
print(y_train.shape)

In [ ]:
dense_weights = np.array([[0.5]])
dense_weights = dense_weights.reshape(1,1)
dense_bias = np.array([1.5])
dense_para = [dense_weights, dense_bias]

print(dense_para)

In [ ]:
Conv2D_layer1_weights = np.array([[[0.12, 0.89, 0.21], [0.04, 0.64, 0.13], [0.91, 0.05, 0.64]]])
Conv2D_layer1_weights = Conv2D_layer1_weights.reshape(3,3,1,1)
Conv2D_layer1_bias = np.array([2])

Conv2D_layer1_para = [Conv2D_layer1_weights, Conv2D_layer1_bias]
print(Conv2D_layer1_para)

In [ ]:
Conv2D_layer2_weights = np.array([[[0.49, 0.98, 0.89], [0.46, 0.47, 0.44], [0.26, 0.65, 0.87]]])
Conv2D_layer2_weights = Conv2D_layer2_weights.reshape(3,3,1,1)
Conv2D_layer2_bias = np.array([2])

Conv2D_layer2_para = [Conv2D_layer2_weights, Conv2D_layer2_bias]
print(Conv2D_layer2_para)

In [ ]:
model = Sequential()
model.add(layers.Conv2D(filters=1,kernel_size=3,strides=1,padding='valid',input_shape=(5,5,1),activation="sigmoid"))
model.layers[0].set_weights(Conv2D_layer1_para)
output = model.predict(x_train)
print(output)
model.add(layers.Conv2D(filters=1,kernel_size=3,strides=1,padding='valid',activation="sigmoid"))
model.layers[1].set_weights(Conv2D_layer2_para)
model.add(layers.Flatten())
model.add(layers.Dense(1, activation="sigmoid"))
model.layers[3].set_weights(dense_para)
print(model.layers[3].get_weights())
print(model.summary())

In [ ]:
# compile model (configure training process)
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.25, momentum=0.0, nesterov=False), loss='mean_squared_error')

In [ ]:
model.fit(x_train, y_train, epochs=1)

In [ ]:
model.layers[0].get_weights()

# Example 3

Convolutional Neural Network with 2D Input
Input: 5x5
Con2D: Kernel=1, Size=3x3, Stride=1
Max: Kernel=1, Size=2x2, Stride=2
Flatten:
SingleNeuron:

In [58]:
x_train_example3 = np.array([[0.61, 0.73, 0.42, 0.97, 0.77, 0.68],
                           [0.80, 0.06, 0.39, 0.11, 0.10, 0.65],
                           [0.95, 0.95, 0.70, 0.57, 0.47, 0.98],
                           [0.32, 0.08, 0.69, 0.02, 0.89, 0.07],
                           [0.58, 0.31, 0.21, 0.03, 0.04, 0.04],
                           [0.93, 0.67, 0.84, 0.7, 0.36, 0.08]])
x_train_example3 = x_train_example3.reshape((1,6,6,1))
y_train = np.array([0.5])

print(x_train_example3.shape)
print(y_train.shape)

(1, 6, 6, 1)
(1,)


In [59]:
dense_weights = np.array([[0.99, 0.93, 0.83, 0.49, 0.59, 0.3, 0.96, 0.72]])
dense_weights = dense_weights.reshape(8,1)
dense_bias = np.array([1.5])
dense_para = [dense_weights, dense_bias]
print(dense_para)

[array([[0.99],
       [0.93],
       [0.83],
       [0.49],
       [0.59],
       [0.3 ],
       [0.96],
       [0.72]]), array([1.5])]


In [60]:
Conv2D_weights = np.array([[[0.12, 0.49, 0.89], [0.98, 0.21, 0.89], [0.04, 0.46, 0.64]],
                           [[0.47, 0.13, 0.44], [0.91, 0.05, 0.64], [0.26, 0.65, 0.87]]])
Conv2D_weights = Conv2D_weights.reshape(3,3,1,2)
Conv2D_bias = np.array([0.95, 1.0])
Conv2D_para = [Conv2D_weights, Conv2D_bias]
print(Conv2D_para)

[array([[[[0.12, 0.49]],

        [[0.89, 0.98]],

        [[0.21, 0.89]]],


       [[[0.04, 0.46]],

        [[0.64, 0.47]],

        [[0.13, 0.44]]],


       [[[0.91, 0.05]],

        [[0.64, 0.26]],

        [[0.65, 0.87]]]]), array([0.95, 1.  ])]


In [61]:
model = Sequential(name='Name')
model.add(layers.Conv2D(filters=2,kernel_size=3, strides=1,padding='valid',input_shape=(6,6,1), activation = "sigmoid"))
model.layers[0].set_weights(Conv2D_para)
output_conv2d = model.predict(x_train_example3)
print(output_conv2d)
max_layer = model.add(layers.MaxPooling2D(pool_size=2, strides=2, padding="valid", name="Maxpool"))
model.add(layers.Flatten())
model.add(layers.Dense(1, activation="sigmoid"))
model.layers[3].set_weights(dense_para)
print(model.layers[3].get_weights())
print(model.summary())

[[[[0.97832537 0.9793546 ]
   [0.97246563 0.9738472 ]
   [0.9686806  0.97608167]
   [0.97079855 0.9855428 ]]

  [[0.93756735 0.97408056]
   [0.9179565  0.938607  ]
   [0.9420676  0.95251083]
   [0.9066161  0.94969326]]

  [[0.95576096 0.97812307]
   [0.93643993 0.9579083 ]
   [0.8841572  0.95653665]
   [0.9089516  0.9575926 ]]

  [[0.96354353 0.96462387]
   [0.96547383 0.9452463 ]
   [0.938005   0.94349706]
   [0.93764925 0.89959204]]]]
[array([[0.99],
       [0.93],
       [0.83],
       [0.49],
       [0.59],
       [0.3 ],
       [0.96],
       [0.72]], dtype=float32), array([1.5], dtype=float32)]
Model: "Name"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 4, 4, 2)           20        
_________________________________________________________________
Maxpool (MaxPooling2D)       (None, 2, 2, 2)           0         
________________________________________________

In [62]:
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.25, momentum=0.0, nesterov=False)
, loss='mean_squared_error')

In [63]:
model.fit(x_train_example3, y_train, epochs=1)

Train on 1 samples
1/1 [==============================] - 0s 324ms/sample - loss: 0.2492


In [64]:
model.layers[3].get_weights()

[array([[0.9898031 ],
        [0.92980283],
        [0.82980454],
        [0.48980162],
        [0.5898056 ],
        [0.2998031 ],
        [0.95981115],
        [0.71980727]], dtype=float32),
 array([1.4997987], dtype=float32)]