In [145]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
import numpy as np

# Example 1

Convolutional Neural Network with 2D Input
Input: 5x5
Con2D: Kernel=1, Size=3x3, Stride=1
Flatten:
SingleNeuron:

In [225]:
# create input data
x_train = np.array([[0.02, 0.21, 0.07, 0.17, 0.78],
                          [0.09, 0.25, 0.78, 0.04, 0.24],
                          [0.97, 0.29, 0.37, 0.27, 0.82],
                          [1.00, 0.29, 0.75, 0.62, 0.56],
                          [0.88, 0.65, 0.09, 0.99, 0.87]])
x_train = x_train.reshape((1,5,5,1))
y_train = np.array([0.5])

In [226]:
# create weights/bias for dense layer
dense_weights = np.array([[0.99, 0.93, 0.83, 0.49, 0.59, 0.3, 0.96, 0.72, 0.8]])
dense_weights = dense_weights.reshape(9,1)
dense_bias = np.array([1.5])
dense_para = [dense_weights, dense_bias]

In [227]:
# create weights/bias for convolutional layer
Conv2D_weights = np.array([[[0.12, 0.89, 0.21], [0.04, 0.64, 0.13], [0.91, 0.05, 0.64]]])
Conv2D_weights = Conv2D_weights.reshape(3,3,1,1)
Conv2D_bias = np.array([1])
Conv2D_para = [Conv2D_weights, Conv2D_bias]

In [228]:
# create model
model = Sequential()
model.add(layers.Conv2D(filters=1,kernel_size=3,strides=1,padding='valid',input_shape=(5,5,1),activation="sigmoid"))
model.layers[0].set_weights(Conv2D_para)
model.add(layers.Flatten())
model.add(layers.Dense(1, activation="sigmoid"))
model.layers[2].set_weights(dense_para)
print(model.summary())

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_21 (Conv2D)           (None, 3, 3, 1)           10        
_________________________________________________________________
flatten_17 (Flatten)         (None, 9)                 0         
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 10        
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
None


In [229]:
# compile model (configure training process)
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.5, momentum=0.0, nesterov=False), loss='mean_squared_error')

In [230]:
# fit model
model.fit(x_train, y_train, epochs=1)

Train on 1 samples
1/1 [==============================] - 0s 337ms/sample - loss: 0.2495


In [231]:
# print final weights/bias per layer
weights = model.layers[2].get_weights()[0]
bias = model.layers[2].get_weights()[1]

print('Fully Connected Layer:')
print("Weights: \n", weights)
print('Bias:', bias)
print()

weights = model.layers[0].get_weights()[0]
weights = weights.reshape((3,3))
bias = model.layers[0].get_weights()[1]

print('Convolutional Layer:')
print("Weights: \n", weights)
print('Bias:', bias)

Fully Connected Layer:
Weights: 
 [[0.98977655]
 [0.9297864 ]
 [0.8297821 ]
 [0.48977062]
 [0.5897749 ]
 [0.29977748]
 [0.9597756 ]
 [0.71976924]
 [0.79977596]]
Bias: [1.49976]

Convolutional Layer:
Weights: 
 [[0.11996782 0.88997495 0.20996019]
 [0.03994639 0.6399565  0.12995407]
 [0.9099442  0.04995092 0.6399453 ]]
Bias: [0.99989593]


# Example 2

Convolutional Neural Network with 2D Input
Input: 5x5
Con2D: Kernel=1, Size=3x3, Stride=1
Con2D: Kernel=1, Size=3x3, Stride=1
Flatten:
SingleNeuron:

In [232]:
# create data
x_train = np.array([[0.02, 0.21, 0.07, 0.17, 0.78],
                          [0.09, 0.25, 0.78, 0.04, 0.24],
                          [0.97, 0.29, 0.37, 0.27, 0.82],
                          [1.00, 0.29, 0.75, 0.62, 0.56],
                          [0.88, 0.65, 0.09, 0.99, 0.87]])
x_train = x_train.reshape((1,5,5,1))
y_train = np.array([0.5])

print(x_train.shape)
print(y_train.shape)

(1, 5, 5, 1)
(1,)


In [233]:
# create weights/bias for dense layer
dense_weights = np.array([[0.5]])
dense_weights = dense_weights.reshape(1,1)
dense_bias = np.array([1.5])
dense_para = [dense_weights, dense_bias]

In [234]:
# create weights/bias for 1st convolutional layer
Conv2D_layer1_weights = np.array([[[0.12, 0.89, 0.21], [0.04, 0.64, 0.13], [0.91, 0.05, 0.64]]])
Conv2D_layer1_weights = Conv2D_layer1_weights.reshape(3,3,1,1)
Conv2D_layer1_bias = np.array([2])
Conv2D_layer1_para = [Conv2D_layer1_weights, Conv2D_layer1_bias]

In [235]:
# create weights/bias for 2nd convolutional layer
Conv2D_layer2_weights = np.array([[[0.49, 0.98, 0.89], [0.46, 0.47, 0.44], [0.26, 0.65, 0.87]]])
Conv2D_layer2_weights = Conv2D_layer2_weights.reshape(3,3,1,1)
Conv2D_layer2_bias = np.array([2])
Conv2D_layer2_para = [Conv2D_layer2_weights, Conv2D_layer2_bias]

In [236]:
# create model
model = Sequential()
model.add(layers.Conv2D(filters=1,kernel_size=3,strides=1,padding='valid',input_shape=(5,5,1),activation="sigmoid"))
model.layers[0].set_weights(Conv2D_layer1_para)
output = model.predict(x_train)
model.add(layers.Conv2D(filters=1,kernel_size=3,strides=1,padding='valid',activation="sigmoid"))
model.layers[1].set_weights(Conv2D_layer2_para)
model.add(layers.Flatten())
model.add(layers.Dense(1, activation="sigmoid"))
model.layers[3].set_weights(dense_para)
print(model.summary())

Model: "sequential_12"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_22 (Conv2D)           (None, 3, 3, 1)           10        
_________________________________________________________________
conv2d_23 (Conv2D)           (None, 1, 1, 1)           10        
_________________________________________________________________
flatten_18 (Flatten)         (None, 1)                 0         
_________________________________________________________________
dense_18 (Dense)             (None, 1)                 2         
Total params: 22
Trainable params: 22
Non-trainable params: 0
_________________________________________________________________
None


In [237]:
# compile model (configure training process)
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.5, momentum=0.0, nesterov=False), loss='mean_squared_error')

In [238]:
# fit model
model.fit(x_train, y_train, epochs=1)

Train on 1 samples
1/1 [==============================] - 0s 386ms/sample - loss: 0.1450


In [239]:
# print final weights/bias per layer
# Fully connected layer
weights = model.layers[3].get_weights()[0]
bias = model.layers[3].get_weights()[1]

print('Fully Connected Layer:')
print("Weights: \n", weights)
print('Bias:', bias)
print()

# 2nd Conv layer
weights = model.layers[1].get_weights()[0]
weights = weights.reshape((3,3))
bias = model.layers[1].get_weights()[1]

print('2nd Convolutional Layer:')
print("Weights: \n", weights)
print('Bias:', bias)
print()

# 1st Conv layer
weights = model.layers[0].get_weights()[0]
weights = weights.reshape((3,3))
bias = model.layers[0].get_weights()[1]

print('1st Convolutional Layer:')
print("Weights: \n", weights)
print('Bias:', bias)

Fully Connected Layer:
Weights: 
 [[0.46003813]]
Bias: [1.4600126]

2nd Convolutional Layer:
Weights: 
 [[0.48998755 0.9799878  0.88998765]
 [0.45998743 0.4699875  0.43998757]
 [0.25998753 0.6499874  0.86998755]]
Bias: [1.9999872]

1st Convolutional Layer:
Weights: 
 [[0.11999948 0.88999957 0.20999917]
 [0.03999903 0.6399991  0.12999927]
 [0.90999913 0.04999909 0.63999885]]
Bias: [1.9999981]


# Example 3

Convolutional Neural Network with 2D Input
Input: 5x5
Con2D: Kernel=1, Size=3x3, Stride=1
Max: Kernel=1, Size=2x2, Stride=2
Flatten:
SingleNeuron:

In [217]:
# create data
x_train_example3 = np.array([[0.61, 0.73, 0.42, 0.97, 0.77, 0.68],
                           [0.80, 0.06, 0.39, 0.11, 0.10, 0.65],
                           [0.95, 0.95, 0.70, 0.57, 0.47, 0.98],
                           [0.32, 0.08, 0.69, 0.02, 0.89, 0.07],
                           [0.58, 0.31, 0.21, 0.03, 0.04, 0.04],
                           [0.93, 0.67, 0.84, 0.7, 0.36, 0.08]])
x_train_example3 = x_train_example3.reshape((1,6,6,1))
y_train = np.array([0.5])

print(x_train_example3.shape)
print(y_train.shape)

(1, 6, 6, 1)
(1,)


In [240]:
# create weights/bias for dense layer
dense_weights = np.array([[0.99, 0.93, 0.83, 0.49, 0.59, 0.3, 0.96, 0.72]])
dense_weights = dense_weights.reshape(8,1)
dense_bias = np.array([1.5])
dense_para = [dense_weights, dense_bias]

In [241]:
# create weights/bias for convolutional layer
Conv2D_weights = np.array([[[0.12, 0.49, 0.89], [0.98, 0.21, 0.89], [0.04, 0.46, 0.64]],
                           [[0.47, 0.13, 0.44], [0.91, 0.05, 0.64], [0.26, 0.65, 0.87]]])
Conv2D_weights = Conv2D_weights.reshape(3,3,1,2)
Conv2D_bias = np.array([0.95, 1.0])
Conv2D_para = [Conv2D_weights, Conv2D_bias]

In [242]:
# create model
model = Sequential(name='Name')
model.add(layers.Conv2D(filters=2,kernel_size=3, strides=1,padding='valid',input_shape=(6,6,1), activation = "sigmoid"))
model.layers[0].set_weights(Conv2D_para)
output_conv2d = model.predict(x_train_example3)
max_layer = model.add(layers.MaxPooling2D(pool_size=2, strides=2, padding="valid", name="Maxpool"))
model.add(layers.Flatten())
model.add(layers.Dense(1, activation="sigmoid"))
model.layers[3].set_weights(dense_para)
print(model.summary())

Model: "Name"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_24 (Conv2D)           (None, 4, 4, 2)           20        
_________________________________________________________________
Maxpool (MaxPooling2D)       (None, 2, 2, 2)           0         
_________________________________________________________________
flatten_19 (Flatten)         (None, 8)                 0         
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 9         
Total params: 29
Trainable params: 29
Non-trainable params: 0
_________________________________________________________________
None


In [243]:
# compile model (configure training process)
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.5, momentum=0.0, nesterov=False), 
              loss='mean_squared_error')

In [244]:
# fit model
model.fit(x_train_example3, y_train, epochs=1)

Train on 1 samples
1/1 [==============================] - 0s 360ms/sample - loss: 0.2492


In [247]:
# print final weights/bias per layer
# Fully connected layer
weights = model.layers[3].get_weights()[0]
bias = model.layers[3].get_weights()[1]

print('Fully Connected Layer:')
print("Weights: \n", weights)
print('Bias:', bias)
print()

# Conv layer
weights = model.layers[0].get_weights()[0]
fm_1 = weights.reshape(9,2)[:,0].reshape(3,3)
fm_1_bias = model.layers[0].get_weights()[1][0]
fm_2 = weights.reshape(9,2)[:,1].reshape(3,3)
fm_2_bias = model.layers[0].get_weights()[1][1]

print('Convolutional Layer:')
print("Weights (feature map 1): \n", fm_1)
print('Bias (feature map 1):', fm_1_bias)
print()
print("Weights (feature map 2): \n", fm_2)
print('Bias (feature map 2):', fm_2_bias)
print()

Fully Connected Layer:
Weights: 
 [[0.9896061 ]
 [0.92960566]
 [0.8296091 ]
 [0.4896032 ]
 [0.58961123]
 [0.29960617]
 [0.9596223 ]
 [0.71961445]]
Bias: [1.4995973]

Convolutional Layer:
Weights (feature map 1): 
 [[0.11996951 0.8899806  0.20996983]
 [0.03998502 0.6399962  0.1299894 ]
 [0.9099624  0.6399651  0.6499711 ]]
Bias (feature map 1): 0.94995165

Weights (feature map 2): 
 [[0.4899835  0.97998434 0.88998157]
 [0.4599926  0.46998858 0.4399926 ]
 [0.04998935 0.25999022 0.86999094]]
Bias (feature map 2): 0.99997526

